In [1]:
!ls ~/personal/models/fathomnet_benthic/mbari-mb-benthic-33k.pt

/Users/per.morten.halvorsen@schibsted.com/personal/models/fathomnet_benthic/mbari-mb-benthic-33k.pt


In [2]:
model_weights_path = "/Users/per.morten.halvorsen@schibsted.com/personal/models/fathomnet_benthic/mbari-mb-benthic-33k.pt"
from yolov5 import YOLOv5

model = YOLOv5(model_weights_path)
model.model

AutoShape(
  (model): DetectMultiBackend(
    (model): DetectionModel(
      (model): Sequential(
        (0): Focus(
          (conv): Conv(
            (conv): Conv2d(12, 80, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
        (1): Conv(
          (conv): Conv2d(80, 160, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(160, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (2): C3(
          (cv1): Conv(
            (conv): Conv2d(160, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(80, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(160, 80, kernel_siz

In [1]:
from fathomnet.models.yolov5 import MBARIMBBenthicModel 

model = MBARIMBBenthicModel()

Using cache found in /Users/per.morten.halvorsen@schibsted.com/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2024-3-14 Python-3.11.5 torch-2.2.1 CPU

Fusing layers... 
Model summary: 476 layers, 91841704 parameters, 0 gradients
Adding AutoShape... 


In [75]:
import ipywidgets as widgets                      # Provides embedded widgets
import requests                                   # Manages HTTP requests
import numpy as np                                # Facilitates array/matrix operations
import plotly.express as px                       # Generates nice plots
import random                                     # Generates pseudo-random numbers
from PIL import Image, ImageFont, ImageDraw       # Facilitates image operations
from io import BytesIO  

from fathomnet.api import boundingboxes, images
from torch import rand

# Get a list of all concepts that have at least 1 bounding box
all_concepts = boundingboxes.find_concepts()

def get_random_image(seed=111):
    # Get the selected concept
    random.seed(seed)
    selected_concept = random.choice(all_concepts) 

    # List the images FathomNet for that concept
    concept_images = images.find_by_concept(selected_concept)

    # Print the total number
    print('Found', len(concept_images), 'images of', selected_concept)

    # Pick a random image
    random_image = random.choice(concept_images) #[random.randrange(len(concept_images))]

    # Fetch and show the image
    image_data = requests.get(random_image.url).content
    pil_image = Image.open(BytesIO(image_data))
    return pil_image, random_image


image, annotaion = get_random_image(111)
labels = annotaion.boundingBoxes

output = model.predict(image)
output.__next__()#.show()
# output.pandas().xyxy[0]


Found 2 images of Evoplosoma forcipifera


BoundingBox(uuid=None, id=None, userDefinedKey=None, concept='Isididae', altConcept=None, image=None, groupOf=None, height=889, occluded=None, observer=None, truncated=None, width=352, x=945, y=1, createdTimestamp=None, lastUpdatedTimestamp=None, verified=None, verifier=None, verificationTimestamp=None)

In [76]:
len(labels)

1

In [79]:
def get_random_image_set(seed=111, limit=10):
    random.seed(seed)
    concept = random.choice(all_concepts)
    print('Selected concept:', concept)
    image_set = images.find_by_concept(concept)
    return image_set[:limit] if len(image_set) > limit else image_set


def load_images(img_set, limit=10):
    img_set = img_set[:limit] if len(img_set) > limit else img_set
    return [Image.open(BytesIO(requests.get(img.url).content)) for img in img_set]


image_set = get_random_image_set(110, 2)
input_images = load_images(image_set)

output = model._model(input_images)
predictions = model.predict(input_images)

detection = predictions.__next__()

Selected concept: Opisthoteuthis sp. A


In [77]:
image_set[1].boundingBoxes

[ABoundingBoxDTO(id=None, uuid='64c16f8c-7060-4118-bb5d-f78c048814ba', userDefinedKey='1f6e592e-d5ec-4b77-5960-ddf7ab44aa1e', concept='Sebastes diploproa', altConcept=None, image=None, groupOf=None, height=54, occluded=None, observer='master@mbari.org', truncated=None, width=124, x=113, y=42, rejected=False, verified=False, verifier=None, verificationTimestamp=None, createdTimestamp=None, lastUpdatedTimestamp='2021-11-01T17:31:13.147Z'),
 ABoundingBoxDTO(id=None, uuid='6389fac4-7a3a-420d-81c3-47e3fa8210c6', userDefinedKey='da0e4cd5-1f50-434c-1e68-379aac44aa1e', concept='Opisthoteuthis sp. A', altConcept=None, image=None, groupOf=None, height=111, occluded=None, observer='master@mbari.org', truncated=None, width=131, x=392, y=193, rejected=False, verified=False, verifier=None, verificationTimestamp=None, createdTimestamp=None, lastUpdatedTimestamp='2021-11-01T17:31:13.157Z'),
 ABoundingBoxDTO(id=None, uuid='9f78d975-f75d-49c6-bb19-4b1bd42276a4', userDefinedKey='52e3fa10-d078-4603-7d66-7

In [26]:
detection.x, detection.y, detection.height, detection.width

(219, 0)

In [67]:
import pandas as pd 


def boundingBox_to_df(boudingBox, suffix=""):
    df = pd.DataFrame(boudingBox, columns=['x', 'y', 'width', 'height', 'concept'])
    df["name"] = df["concept"]
    df.drop(columns=["concept"], inplace=True)
    return xywh2xyxy(df, suffix=suffix)


def xywh2xyxy(df, suffix=""):
    suffix = suffix if suffix == "" else "_"+suffix

    df["xmin"+suffix] = df["x"]
    df["ymin"+suffix] = df["y"]
    df["xmax"+suffix] = df["x"] + df["width"]
    df["ymax"+suffix] = df["y"] + df["height"]
    
    df.drop(columns=["x", "y", "width", "height"], inplace=True)
    return df

boundingBox_to_df(image_set[0].boundingBoxes, "true")

name  xmin_true  ymin_true  xmax_true  ymax_true
0    Sebastes diploproa        221          4        520        188
1  Opisthoteuthis sp. A        277        173        571        422

In [69]:
for pred, true in zip(output.pandas().xyxy, image_set):
    display(pred[['xmin', 'ymin', 'xmax', 'ymax', 'confidence', 'name']])
    display(boundingBox_to_df(true.boundingBoxes, "true"))

xmin      ymin        xmax        ymax  confidence  \
0  219.830902  0.410709  511.329468  194.407013     0.87654   

                 name  
0  Sebastes diploproa

name  xmin_true  ymin_true  xmax_true  ymax_true
0    Sebastes diploproa        221          4        520        188
1  Opisthoteuthis sp. A        277        173        571        422

xmin        ymin        xmax        ymax  confidence  \
0  455.788788  390.357239  647.474426  477.489929    0.835590   
1  293.533508  268.095673  360.526489  316.166077    0.776905   
2  300.874634   77.290291  395.863953  164.801865    0.770832   
3  117.978973   41.733334  226.943726   99.646461    0.732620   
4   65.102600  150.227310  121.769966  187.480225    0.728061   
5   87.516327  328.065247  162.514908  380.641724    0.660179   
6  568.123596   42.363354  614.046204   73.622284    0.436319   
7  616.686768   42.956657  666.671753   75.432411    0.337282   
8  123.350273   91.200195  166.369171  119.268677    0.262469   

                          name  
0           Sebastes diploproa  
1  Strongylocentrotus fragilis  
2           Sebastes diploproa  
3           Sebastes diploproa  
4  Strongylocentrotus fragilis  
5  Strongylocentrotus fragilis  
6  Strongylocentrotus fragilis  
7  Strongylocentrotus fragilis  
8  Strongylocentrotus fragilis

name  xmin_true  ymin_true  xmax_true  ymax_true
0           Sebastes diploproa        113         42        237         96
1         Opisthoteuthis sp. A        392        193        523        304
2  Strongylocentrotus fragilis         61        150        123        188
3           Sebastes diploproa        450        392        644        476
4  Strongylocentrotus fragilis         83        328        163        381
5  Strongylocentrotus fragilis        294        267        359        315
6           Sebastes diploproa        300         77        395        164

In [62]:
def unpack_label(box):
    return box.x, box.y, box.x + box.width, box.y + box.height

def unpack_pred(pred):
    return pred.xmin, pred.ymin, pred.xmax, pred.ymax

In [70]:
def calculate_iou(box1, box2):
    # Calculate intersection coordinates
    x1_intersection = max(box1[0], box2[0])
    y1_intersection = max(box1[1], box2[1])
    x2_intersection = min(box1[2], box2[2])
    y2_intersection = min(box1[3], box2[3])

    # Calculate intersection area
    intersection_area = max(0, x2_intersection - x1_intersection) * max(0, y2_intersection - y1_intersection)

    # Calculate area of each box
    box1_area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2_area = (box2[2] - box2[0]) * (box2[3] - box2[1])

    # Calculate union area
    union_area = box1_area + box2_area - intersection_area

    # Calculate IoU
    iou = intersection_area / union_area if union_area > 0 else 0

    return iou


In [71]:
labels

[ABoundingBoxDTO(id=None, uuid='2d4bebde-863f-4dfb-aaeb-5bdbb6feea21', userDefinedKey=None, concept='Evoplosoma forcipifera', altConcept=None, image=None, groupOf=None, height=750, occluded=None, observer=None, truncated=None, width=1000, x=0, y=0, rejected=False, verified=False, verifier=None, verificationTimestamp=None, createdTimestamp=None, lastUpdatedTimestamp='2022-10-31T14:45:53.482Z')]

In [84]:
for pred_box in output.xyxy:
    print(pred_box[:4])

[[     219.83     0.41071      511.33      194.41     0.87654         131]]
[[     455.79      390.36      647.47      477.49     0.83559         131]
 [     293.53       268.1      360.53      316.17     0.77691          25]
 [     300.87       77.29      395.86       164.8     0.77083         131]
 [     117.98      41.733      226.94      99.646     0.73262         131]]


In [80]:
iou_threshold = 0.5

tp = 0  # True positives
fp = 0  # False positives
fn = 0  # False negatives
ious = []

labels = [x.boundingBoxes for x in image_set]

for pred_box in output.xyxy:
    pred_box_coords = pred_box[:4]
    pred_class_id = int(pred_box[5])

    # Find best matching true box
    best_iou = 0
    best_match_index = -1
    for i, true_box in enumerate(labels):
        true_box_coords = unpack_label(true_box)
        iou = calculate_iou(pred_box_coords, true_box_coords)
        if iou > best_iou:
            best_iou = iou
            best_match_index = i

    # If the best match has IoU > 0.5, it's a true positive
    if best_iou > 0.5:
        tp += 1
        ious.append(best_iou)
        # Remove the matched true box
        del labels[best_match_index]
    else:
        fp += 1

    ious.append(best_iou)


# All remaining true boxes are false negatives
fn = len(labels)

tp, fp, fn

IndexError: index 5 is out of bounds for dimension 0 with size 1

In [ ]:
output.show()
for i in range(len(output)):
    display(output.pandas().xyxy[i])
    print(labels[i].show())
    print('---')

In [18]:
output.pandas().xyxy[2]

xmin        ymin        xmax        ymax  confidence  class  \
0   431.172302  409.953735  514.427551  486.000000    0.812776    131   
1   331.143829  146.889206  394.478149  183.599823    0.790740    131   
2   452.281342  330.043884  544.250793  378.892029    0.764649    131   
3   397.070679  407.703339  439.049957  444.322571    0.748020     25   
4   169.206375  212.686005  199.644211  235.582870    0.742796     25   
5   563.477478  234.050034  603.548096  263.029877    0.733648     25   
6   607.633118  173.926254  673.567627  210.915237    0.725349    131   
7   191.451401  184.210480  223.113144  206.593353    0.719655     25   
8   110.024353  333.279510  145.500458  359.845062    0.711817     25   
9   192.343384  297.088196  226.430817  321.737701    0.700830     25   
10  154.903870  271.126587  187.381271  296.964966    0.695622     25   
11  394.191956  209.581039  426.386505  233.351196    0.615782     25   
12  120.984520  397.194977  158.894119  427.004913    0.605157     25   
13  403.933594  450.938141  441.845184  482.754028    0.252639     25   

                           name  
0            Sebastes diploproa  
1            Sebastes diploproa  
2            Sebastes diploproa  
3   Strongylocentrotus fragilis  
4   Strongylocentrotus fragilis  
5   Strongylocentrotus fragilis  
6            Sebastes diploproa  
7   Strongylocentrotus fragilis  
8   Strongylocentrotus fragilis  
9   Strongylocentrotus fragilis  
10  Strongylocentrotus fragilis  
11  Strongylocentrotus fragilis  
12  Strongylocentrotus fragilis  
13  Strongylocentrotus fragilis

In [ ]:


def color_for_concept(concept: str):
  hash = sum(map(ord, concept)) << 5
  return f'hsl({hash % 360}, 100%, 85%)'



def load_annotations_for_image(image):
    draw_image = ImageDraw.Draw(Image.open(BytesIO(requests.get(image.url).content)))

    for box in image.boundingBoxes:
        color = color_for_concept(box.concept)
        draw_image.rectangle((box.x, box.y, box.x + box.width, box.y + box.height), width=3, outline=color)
        draw_image.text((box.x, box.y + box.height), box.concept, fill=color)

    return image
    
    
def load_annotations(image_set):
    return [load_annotations_for_image(img) for img in image_set]


# DeepSORT

In [3]:
import os 
from pathlib import Path

if Path(os.getcwd()).stem == "notebooks":
    os.chdir("..")
    print(f"Changed working directory to {os.getcwd()}")

Changed working directory to /Users/per.morten.halvorsen@schibsted.com/personal/ocean-species-identification


In [4]:
from deep_sort_realtime.deepsort_tracker import DeepSort
from src.ObjectTrackingDeepSORT import YoloDetector

import cv2
import numpy as np
import sys
import glob

import time
import torch


2024-03-14 18:23:09.226 python[7308:2354604] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
Using cache found in /Users/per.morten.halvorsen@schibsted.com/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2024-3-14 Python-3.11.5 torch-2.2.1 CPU

Fusing layers... 
YOLOv5s summary: 270 layers, 7235389 parameters, 0 gradients, 16.6 GFLOPs
Adding AutoShape... 


Using Device:  cpu


In [5]:
detector = YoloDetector(model_name=model_weights_path)

Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /Users/per.morten.halvorsen@schibsted.com/.cache/torch/hub/master.zip
YOLOv5 🚀 2024-3-14 Python-3.11.5 torch-2.2.1 CPU

Fusing layers... 
Model summary: 607 layers, 91887384 parameters, 0 gradients
Adding AutoShape... 


Using Device:  cpu


In [6]:
detector.model.classes

In [6]:
cap = cv2.VideoCapture(0)

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

True

In [15]:
object_tracker = DeepSort(
    max_age=5,
    n_init=2,
    nms_max_overlap=1.0,
    max_cosine_distance=0.3,
    nn_budget=None,
    override_track_class=None,
    embedder="mobilenet",
    half=True,
    bgr=True,
    embedder_gpu=True,
    embedder_model_name=None,
    embedder_wts=None,
    polygon=False,
    today=None
)


In [16]:
while cap.isOpened():

    succes, img = cap.read()
 
    start = time.perf_counter()
    
    results = detector.score_frame(img)
    img, detections = detector.plot_boxes(results, img, height=img.shape[0], width=img.shape[1], confidence=0.5)

        
    tracks = object_tracker.update_tracks(detections, frame=img) # bbs expected to be a list of detections, each in tuples of ( [left,top,w,h], confidence, detection_class )
    
        
    for track in tracks:
        if not track.is_confirmed():
            continue
        track_id = track.track_id
        ltrb = track.to_ltrb()
        
        bbox = ltrb
        
        cv2.rectangle(img,(int(bbox[0]), int(bbox[1])),(int(bbox[2]), int(bbox[3])),(0,0,255),2)
        cv2.putText(img, "ID: " + str(track_id), (int(bbox[0]), int(bbox[1] - 10)), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
    
    
        
    end = time.perf_counter()
    totalTime = end - start
    fps = 1 / totalTime


    cv2.putText(img, f'FPS: {int(fps)}', (20,70), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0,255,0), 2)
    cv2.imshow('img',img)


    if cv2.waitKey(1) & 0xFF == 27:
        break

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/training/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/9t/2ktxww317sjf49by2n8qnpb80000gp/T/ipykernel_95599/4165312606.py", line 7, in <module>
    results = detector.score_frame(img)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/per.morten.halvorsen@schibsted.com/personal/ocean-species-identification/src/ObjectTrackingDeepSORT.py", line 41, in score_frame
    results = self.model(frame)
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/training/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/training/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520,

In [ ]:
# Release and destroy all windows before termination
cap.release()

cv2.destroyAllWindows()

# SORT

In [13]:
import os 
from pathlib import Path 
import subprocess

# move to upper repo to not download a repo inside a repo
os.chdir("/Users/per.morten.halvorsen@schibsted.com/personal/")
assert Path(os.getcwd()).stem == "personal"

# clone repo, install requirements
subprocess.run(["git", "clone", "https://github.com/abewley/sort.git"], check=True)
# subprocess.run(["pip", "install", "-r", "sort/requirements.txt"], check=True)

# import all modules in sort
from sort.sort import *

Cloning into 'sort'...
remote: Enumerating objects: 208, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 208 (delta 2), reused 2 (delta 1), pack-reused 202
Receiving objects: 100% (208/208), 1.21 MiB | 4.20 MiB/s, done.
Resolving deltas: 100% (74/74), done.


In [15]:

# subprocess.run(["git", "clone", "https://github.com/abewley/sort.git"], check=True)
subprocess.run(["pip", "install", "-r", "sort/requirements.txt"], check=True)

Looking in indexes: https://per.morten.halvorsen%40schibsted.com:****@artifacts.schibsted.io/artifactory/api/pypi/pypi-virtual/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.8/29.8 MB 25.2 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 16.4 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 22.0 MB/s eta 0:00:0000:0100:01
  Running setup.py clean for scikit-image


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [697 lines of output]
      /private/var/folders/9t/2ktxww317sjf49by2n8qnpb80000gp/T/pip-install-2w597vfp/scikit-image_aaca6cb53dc2443ca8c014c5ee699688/setup.py:159: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.core import setup
      /opt/homebrew/Caskroom/miniconda/base/envs/training/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ************

  Running setup.py clean for lap
Failed to build scikit-image lap


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [174 lines of output]
      /private/var/folders/9t/2ktxww317sjf49by2n8qnpb80000gp/T/pip-install-2w597vfp/lap_662a339128e14aa6b3cd9b1e9f656d4f/setup.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Partial import of lap during the build process.
      /private/var/folders/9t/2ktxww317sjf49by2n8qnpb80000gp/T/pip-install-2w597vfp/lap_662a339128e14aa6b3cd9b1e9f656d4f/setup.py:223: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          

CalledProcessError: Command '['pip', 'install', '-r', 'sort/requirements.txt']' returned non-zero exit status 1.

In [16]:
mot_tracker = Sort() 


In [21]:
vid_dir = "/Users/per.morten.halvorsen@schibsted.com/data/TrashCan/dataset/original_data/images/"

vid_000077 = [
    Path(vid_dir) / file 
    for file in 
    os.listdir(vid_dir)
    if "vid_000077" in file
]
len(vid_000077)

43

In [22]:
detections = model.model(vid_000077)


In [27]:
track_bbs_ids = mot_tracker.update(detections.pred)


TypeError: list indices must be integers or slices, not tuple

In [32]:
track_bbs_ids = mot_tracker.update([p.numpy() for p in detections.pred][2])
track_bbs_ids.tolist()

[]